name: Run Terraform Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to run'     
        required: true
      environment:
        description: 'Environment to run against'
        required: true
        default: production

env:
  ENVIRONMENT: ${{ inputs.environment }}
  key_prefix: "neosim"
  tf_actions_working_dir: terraform

jobs:
  terraform_apply:
    name: Run Terraform command
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init
      env:
        TF_CLI_ARGS_init: -backend-config="${{ env.key_prefix }}/${{ env.ENVIRONMENT }}/terraform.tfstate" 
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Command
      id: apply
      run: terraform ${{ inputs.command }}
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_environment: ${{ env.ENVIRONMENT }}
